# Generated by Django 4.0.4 on 2022-06-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vick', '0002_flowers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
