# Generated by Django 4.0.4 on 2022-06-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vick', '0003_calor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('dats', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Calor',
        ),
        migrations.DeleteModel(
            name='Flowers',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
